### ISSUE TITLE
Unify `Rescale` and `RescaleCyc`

### ISSUE THREAD

**Issue by crockeea** [cpeikert/Lol#14]
`RescaleCyc` nominally lets us supply the rescaling basis, but this can be done with `Rescale` by rescaling tagged `Cyc` elements (note: this should allow a `Rescale(Cyc)` instance for `UCyc C`.)

The main challenge in removing the class is that we currently have overlapping instances, which seem inherent due to having a different algorithm for product rings. This means that the compiler can't tell that we have a `Rescale` instance if `m` changes. If we did not have overlapping instances, `m` could appear in the instance head and GHC could still deduce the constraint. 

It's unclear how to move forward on this issue, but we all agree that it would be better if `RescaleCyc` didn't have to exist.

**Comment by cpeikert** [comment]
We'd still love to avoid this, but the fact that there's a special algorithm for rescaling pairs means we need polymorphism, which means we need a class.
