### ISSUE TITLE
Remove `IntegralDomain` from `divG`

### ISSUE THREAD

**Issue by crockeea** [cpeikert/Lol#17]
We currently need a bogus instance of `IntegralDomain` for product rings in order to be able to call `divG`. This instance fails at runtime when `oddRadical m` is not invertible mod `p`. for example if we try to use a "bad" plaintext modulus with SHE. The error in that case would be a runtime error about a failure of `modInv`, but we would instead like a more meaningful error saying something about the necessary conditions that are violated.  We proposed a special class like `CRTrans` that just supplies `divModOddRad`.

**Comment by cpeikert** [comment]
This issue is resolved by the (not-so-)recent refactoring that makes the base type an argument to the `TensorG` class, and makes `Cyclotomic` require a fully applied type.
