### ISSUE TITLE
Please list all .proto files needed to read the challenges

### ISSUE THREAD

**Issue by haochenuw** [cpeikert/Lol#30]
Are the two files challenges.proto and RLWE.proto all one needs to read the challenges? And please specify which should be used to read the .challenge file and which for the .instance file. 

Could you give an example code reading the instance in C or C++? (or actually in any language). It'll be super helpful. Thanks!

**Comment by crockeea** [comment]
The proto files `Challenges.proto` and `RLWE.proto` from [the challenge website](https://web.eecs.umich.edu/~cpeikert/rlwe-challenges/) should suffice for reading into another language. (Note that after publishing the challenges, we reorganized things a bit, so the proto files look different on the HEAD of master, but that only matters if you are using Lol.)

`*.challenge` files should be read with the `Challenge` message type in `Challenge.proto`. Part of that message is the type of instance for the challenge. For example, if `params` is a `ContParams`, then the instances for that challenge should be read with the `InstanceCont` message type.

**Comment by crockeea** [comment]
On Debian, I installed the `protobuf-compiler` package, which includes the `protoc` program. This allows you to compile proto files into C++, Java, or Python code that parses our challenges.

For the current HEAD of the master branch, I did the following:

```
> cd lol
> protoc Lol.proto RLWE.proto --cpp_out=../chall-cpp --java_out=../chall-java --python_out=../chall-python
> cd ../rlwe-challenges
> protoc Challenges.proto -I. -I../lol --cpp_out=../chall-cpp --java_out=../chall-java --python_out=../chall-python
```
This produced code to parse the challenges in C++, Java, and Python.

**Comment by crockeea** [comment]
The following python code loads and prints the challenge parameters (in the `.challenge` file), one instance in the challenge, and the corresponding secret. (`Challenges_pb2` was auto-generated in the last comment.)

```
import Challenges_pb2
import sys

chall = Challenges_pb2.Challenge()
f = open("../chall-id0000-rlwec-m256-q769-l3-short-toy.challenge", "rb")
chall.ParseFromString(f.read())
f.close()
print chall

inst = Challenges_pb2.InstanceCont1()
f = open("../chall-id0000-rlwec-m256-q769-l3-short-toy-00.instance", "rb")
inst.ParseFromString(f.read())
f.close()
print inst

secret = Challenges_pb2.Secret1()
f = open("../chall-id0000-rlwec-m256-q769-l3-short-toy-00.secret", "rb")
secret.ParseFromString(f.read())
f.close()
print secret
```

**Comment by haochenuw** [comment]
First thank you for your detailed reply! Yet when I ran 
`
protoc Lol.proto RLWE.proto --cpp_out=../chall-cpp --java_out=../chall-java --python_out=../chall-python`

I got Lol.proto: No such file or directory

**Comment by haochenuw** [comment]
update: I removed Lol.proto from the above line, and I got a new error:
`
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: RLWE.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
`

**Comment by crockeea** [comment]
The reason you couldn't find Lol.proto is because you were using the proto files from the challenge website, where there are only two files. 

I've  not seen the warning about the proto version, but proto2 should work.

**Comment by haochenuw** [comment]
I added syntax="proto2" to all 3 proto files and got it to work. Thanks!
