### ISSUE TITLE
Precision with at least one bad modulus

### ISSUE THREAD

**Issue by crockeea** [cpeikert/Lol#31]
We must be careful when _any_ moduli in a product are "bad" (not prime and 1 mod m). This is because our current representation forces _all_ components to work over `Complex Double`, thus limiting their size to ~25 bits, rather than the expected ~31 bits.

It would be nice if the "good" components of the modulus could be represented with their integer CRT, while the bad components would continue to be represented with Complex Double. This would allow the good moduli to be a full 31 bits (bad moduli are still restricted to 25). To achieve this, we probably need to represent a Cyc over a ring product as a product of Cycs (using a data family?).

**Comment by cpeikert** [comment]
This is now accomplished thanks to `Cyc` being a data family.
