### ISSUE TITLE
Weaken CElt

### ISSUE THREAD

**Issue by crockeea** [cpeikert/Lol#8]
Currently, `CElt` is a catch-all constraint synonym. The result is a dishonest interface that overly-restricts functions and instances (i.e., requiring `NFData` to get a random sample or to add two ring elts). We fixed up `TElt`; `CElt` should be analogous for` UCyc`/`Cyc`: it should contain constraints need to hold the tensor (`Tensor t`, `TElt t r` and `TElt (CRTExt r)`), as well as to change bases (`CRTrans r`), but probably not `Random r`, `Eq r`, `NFData r`, etc. Unfortunately, due to `RT`'s implementation of `divGCRT`, changing bases requires `ID r` and `ZT r`.

**Comment by cpeikert** [comment]
I think this is now resolved: `ID r` and `ZT r` are now gone from the `Tensor` methods, thanks to better `divG` algorithms.

**Comment by crockeea** [comment]
Resolved by 24691267177adf95244a5c793894f4ea905c1f56
