### ISSUE TITLE
Include index parameter in `CRTrans`?

### ISSUE THREAD

**Issue by cpeikert** [cpeikert/Lol#9]
Currently, class `CRTrans r` takes just one argument (the base ring `r`), and its method `crtInfo :: Int -> Maybe (CRTInfo r)` takes the index of the CRT.  At some point there may have been a good reason for having this argument, but currently I don't see it.

We should consider changing the class to `CRTrans m r`, possibly with a `Reflects m Int` superclass (but maybe not).  Then `crtInfo` would have type `TaggedT m Maybe (CRTInfo r)`, or perhaps `Tagged m (Maybe (CRTInfo r))`.  This tagging seems much more natural and consistent with what we do elsewhere in the code.

Before attempting this change, we should check the existing `CRTrans` instances and usages.  For example, we'll need instances where the argument `m` may have kind `Factored`, `PrimePower`, or `Nat`.  We already have similar (non-overlapping) instances for `Reflects`, so I don't think this presents any problem.

**Comment by crockeea** [comment]
I think this issue is resolved by https://github.com/cpeikert/Lol/commit/90295fd60fc6dc58289fae2da6aad234bf6c38d3.

**Comment by cpeikert** [comment]
Agreed; we can close this.
